name: data update

on:
  schedule:
    - cron: '* 0 * * *' #UTC

jobs:
  data_update:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy/resources
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: clone
        run: git clone --depth 1 https://github.com/covid19-kitakyushu/covid19-data-updater.git data_setup
      - name: create data
        run: |
          cd $GITHUB_WORKSPACE/data_setup
          npm install
          node main.js
          cd $GITHUB_WORKSPACE
          cp -f ./data_setup/data.json ./data/data.json
          cp -f ./data_setup/news.json ./data/news.json
          rm -rf data_setup
          git config --global user.email secrets.USER_EMAIL
          git config --global user.name UPDATE_BOT
          git add .
          git commit -m 'UPDATE DATA'
          git push origin deploy/resources
