name: data update

on:
  schedule:
    - cron: '0 * * * *' #UTC

jobs:
  data_update:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy/resources
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: clone
        run: git clone --depth 1 https://github.com/covid19-kitakyushu/covid19-data-updater.git data_setup
      - name: update
        run: |
          cd $GITHUB_WORKSPACE/data_setup
          npm install
          node main.js
          cd $GITHUB_WORKSPACE
          cp -f ./data_setup/data.json ./data/data.json
          cp -f ./data_setup/news.json ./data/news.json
          rm -rf data_setup
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: deploy/resources
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATA to deploy/resources
          base: deploy/resources
          branch: deploy/resources
          labels: auto_merge
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
